spring:
  # 文件上传大小限制，spring.http过期了，使用这种方式也可以
  servlet:
    multipart:
      enabled: true
      max-file-size: 10Mb
      max-request-size: 10Mb
  profiles:
      active: dev
async:
  executor:
    thread:
      core_pool_size: 10
      max_pool_size: 200
      queue_capacity: 100000
# 日志配置文件
logging:
  config: classpath:log4j/log4j2.xml




